# Generated by Django 4.1.3 on 2022-11-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule', models.CharField(default='', max_length=50)),
                ('isocode', models.CharField(default='', max_length=50)),
                ('velocity', models.CharField(default='', max_length=50)),
                ('thermal', models.CharField(default='', max_length=50)),
                ('profile', models.CharField(default='', max_length=50)),
                ('temperature', models.CharField(default='', max_length=50)),
                ('log_columndensity', models.CharField(default='', max_length=50)),
                ('emission', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Normalized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule', models.CharField(default='', max_length=50)),
                ('isocode', models.IntegerField()),
                ('velocity', models.CharField(default='', max_length=50)),
                ('thermal', models.CharField(default='', max_length=50)),
                ('profile', models.CharField(default='', max_length=50, unique=True)),
                ('temperature', models.CharField(default='', max_length=8)),
                ('log_columndensity', models.CharField(default='', max_length=50)),
                ('normalized', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Wavelength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oversampling', models.CharField(default='', max_length=50)),
                ('resolution', models.CharField(default='', max_length=50)),
                ('wavelength', models.TextField()),
            ],
        ),
    ]
