# Generated by Django 4.1.3 on 2022-11-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_remove_normalized_normalized_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalized',
            old_name='normalized_float',
            new_name='normalized',
        ),
    ]
