# Generated by Django 4.1.3 on 2022-11-27 21:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0003_rename_normalized_float_normalized_normalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='emission',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='emission',
            name='isocode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emission',
            name='log_columndensity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emission',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emission',
            name='thermal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emission',
            name='velocity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='normalized',
            name='isocode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='normalized',
            name='log_columndensity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='normalized',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='normalized',
            name='thermal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='normalized',
            name='velocity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wavelength',
            name='oversampling',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wavelength',
            name='resolution',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wavelength',
            name='wavelength',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
